### ISSUE TITLE
Wallet storage error occurred\n

### ISSUE THREAD

**Issue by raymondfx** [AnonSolutions/django-indy-community#40]
I get this error when I try to start indy_community_demo

```indy-django_1        | config_file = ['./trustee-org.yml']
indy-django_1        | /home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_orgs.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
indy-django_1        |   orgs = yaml.load(stream)
indy-django_1        | Traceback (most recent call last):
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/wallet_utils.py", line 49, in create_wallet
indy-django_1        |     run_coroutine_with_args(wallet.create_wallet, wallet_config_json, wallet_credentials_json)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/utils.py", line 91, in run_coroutine_with_args
indy-django_1        |     return loop.run_until_complete(coroutine(*args))
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
indy-django_1        |     return future.result()
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
indy-django_1        |     create_wallet.cb)
indy-django_1        | indy.error.IndyError: (<ErrorCode.WalletStorageError: 210>, {'backtrace': '', 'message': 'Error: Wallet storage error occurred\n  Caused by: Plugin returned error\n'})
indy-django_1        | 
indy-django_1        | During handling of the above exception, another exception occurred:
indy-django_1        | 
indy-django_1        | Traceback (most recent call last):
indy-django_1        |   File "manage.py", line 15, in <module>
indy-django_1        |     execute_from_command_line(sys.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
indy-django_1        |     utility.execute()
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
indy-django_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
indy-django_1        |     self.execute(*args, **cmd_options)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
indy-django_1        |     output = self.handle(*args, **options)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_orgs.py", line 91, in handle
indy-django_1        |     org = org_signup(user, password, name, org_attrs=org_attrs, org_relation_attrs=relation_attrs, org_role=org_role, org_ico_url=ico_url)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/registration_utils.py", line 74, in org_signup
indy-django_1        |     org = org_provision(org, raw_password, org_role)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/registration_utils.py", line 37, in org_provision
indy-django_1        |     res = create_wallet(wallet_name, raw_password)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/wallet_utils.py", line 53, in create_wallet
indy-django_1        |     return error_code
indy-django_1        | NameError: name 'error_code' is not defined
indy-django_1        | Loading libindystrgpostgres.so
indy-django_1        | Loading libnullpay.so
indy-django_1        | Getting started -> started
indy-django_1        | Open Pool Ledger: pool1
indy-django_1        | /tmp/indy/pool1.txn
indy-django_1        | Returned pool handle 1
indy-django_1        | App is ready!!!
indy-django_1        | config_file = ['./test-schemas.yml']
indy-django_1        | /home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_schemas.py:33: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
indy-django_1        |   schemas = yaml.load(stream)
indy-django_1        | issue schemas for org_id = 1
indy-django_1        | Traceback (most recent call last):
indy-django_1        |   File "manage.py", line 15, in <module>
indy-django_1        |     execute_from_command_line(sys.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
indy-django_1        |     utility.execute()
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
indy-django_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
indy-django_1        |     self.execute(*args, **cmd_options)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
indy-django_1        |     output = self.handle(*args, **options)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_schemas.py", line 64, in handle
indy-django_1        |     schema = create_schema(org.wallet, schema_json, creddef_template)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/agent_utils.py", line 133, in create_schema
indy-django_1        |     config_json = wallet.wallet_config
indy-django_1        | AttributeError: 'NoneType' object has no attribute 'wallet_config'
indy-django_1        | Loading libindystrgpostgres.so
indy-django_1        | Loading libnullpay.so
indy-django_1        | Getting started -> started
indy-django_1        | Open Pool Ledger: pool1
indy-django_1        | /tmp/indy/pool1.txn
indy-django_1        | Returned pool handle 1
indy-django_1        | App is ready!!!
indy-django_1        | config_file = ['./test-orgs.yml']
indy-django_1        | /home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_orgs.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
indy-django_1        |   orgs = yaml.load(stream)
indy-django_1        | Traceback (most recent call last):
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/wallet_utils.py", line 49, in create_wallet
indy-django_1        |     run_coroutine_with_args(wallet.create_wallet, wallet_config_json, wallet_credentials_json)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/utils.py", line 91, in run_coroutine_with_args
indy-django_1        |     return loop.run_until_complete(coroutine(*args))
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
indy-django_1        |     return future.result()
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/indy/wallet.py", line 61, in create_wallet
indy-django_1        |     create_wallet.cb)
indy-django_1        | indy.error.IndyError: (<ErrorCode.WalletStorageError: 210>, {'backtrace': '', 'message': 'Error: Wallet storage error occurred\n  Caused by: Plugin returned error\n'})
indy-django_1        | 
indy-django_1        | During handling of the above exception, another exception occurred:
indy-django_1        | 
indy-django_1        | Traceback (most recent call last):
indy-django_1        |   File "manage.py", line 15, in <module>
indy-django_1        |     execute_from_command_line(sys.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
indy-django_1        |     utility.execute()
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
indy-django_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
indy-django_1        |     self.execute(*args, **cmd_options)
indy-django_1        |   File "/home/indy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
indy-django_1        |     output = self.handle(*args, **options)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/management/commands/loads_orgs.py", line 91, in handle
indy-django_1        |     org = org_signup(user, password, name, org_attrs=org_attrs, org_relation_attrs=relation_attrs, org_role=org_role, org_ico_url=ico_url)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/registration_utils.py", line 74, in org_signup
indy-django_1        |     org = org_provision(org, raw_password, org_role)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/registration_utils.py", line 37, in org_provision
indy-django_1        |     res = create_wallet(wallet_name, raw_password)
indy-django_1        |   File "/home/indy/indy_community_demo/indy_community_demo/indy_community/wallet_utils.py", line 53, in create_wallet
indy-django_1        |     return error_code```

**Comment by ianco** [comment]
HI @raymondfx possibly there is an error starting the postgres database?  (Or possibly a timing issue that the agent is starting up faster than the database.)  Can you include a full listing of the docker logs?

FYI the django-indy-community code is no longer being supported, there is a new project based on the aries framework (aries is an agent framework that runs on top of indy) that is being actively supported, you can find it here:

https://github.com/AnonSolutions/django-aries-community
